server:
  port: 8081
spring:
  application:
    name: User
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: james

#Hibernate
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
    hibernate:
      ddl-auto: update
