package ca.techacademy.users.util;

import lombok.extern.slf4j.Slf4j;
import org.passay.CharacterData;
import org.passay.CharacterRule;
import org.passay.EnglishCharacterData;
import org.passay.PasswordGenerator;
import org.springframework.stereotype.Component;
@Slf4j
@Component
public class GeneratorImpl implements Generator{
    @Override
    public String getAutoGeneratedPassword() {
        return generatePassword();
    }

    private String generatePassword(){

        PasswordGenerator passwordGenerator = new PasswordGenerator();

        CharacterRule lowerCaseCharacters = new CharacterRule(EnglishCharacterData.LowerCase);
        lowerCaseCharacters.setNumberOfCharacters(3);
        CharacterRule upperCaseCharacters = new CharacterRule(EnglishCharacterData.UpperCase);
        upperCaseCharacters.setNumberOfCharacters(3);
        CharacterRule digits = new CharacterRule(EnglishCharacterData.Digit);
        digits.setNumberOfCharacters(3);
        CharacterRule specialCharacters = new CharacterRule(new CharacterData() {
            @Override
            public String getErrorCode() {
                return "SAMPLE_ERROR_CODE";
            }

            @Override
            public String getCharacters() {
                return "!@%&><.#?$";
            }
        });
        specialCharacters.setNumberOfCharacters(1);
        return passwordGenerator.generatePassword(12, lowerCaseCharacters, upperCaseCharacters, digits, specialCharacters);
    }
}
